name: "Validate PR Title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        shell: bash
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          # Valid types
          VALID_TYPES: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            release
          # Valid scopes categorized by area
          VALID_SCOPES: |
            # Security
            vuln
            misconf
            secret
            license

            # Core features
            image
            fs
            repo
            sbom
            server
            k8s
            aws
            vm
            plugin

            # OS
            alpine
            wolfi
            chainguard
            redhat
            alma
            rocky
            mariner
            oracle
            debian
            ubuntu
            amazon
            suse
            photon
            distroless
            windows

            # Languages
            ruby
            php
            python
            nodejs
            rust
            dotnet
            java
            go
            c
            c++
            elixir
            dart
            swift
            bitnami
            conda
            julia

            # Categories
            os
            lang

            # IaC
            kubernetes
            dockerfile
            terraform
            cloudformation

            # Container
            docker
            podman
            containerd
            oci

            # Misc
            cli
            flag
            cyclonedx
            spdx
            purl
            vex
            helm
            report
            db
            parser
            deps
        run: |
          set -euo pipefail

          # Convert env vars to regex alternatives, excluding comments and empty lines
          TYPES_REGEX=$(echo "$VALID_TYPES" | grep -v '^$' | paste -sd '|')
          SCOPES_REGEX=$(echo "$VALID_SCOPES" | grep -v '^$' | grep -v '^#' | paste -sd '|')
          
          # Regular expression for conventional commits format
          # Format: <type>(<scope>): <description> or <type>: <description>
          # Also allows for breaking changes with '!'
          CONVENTIONAL_COMMIT_REGEX="^(${TYPES_REGEX})(\(${SCOPES_REGEX}\))?!?: .+$"
          
          if ! echo "$PR_TITLE" | grep -qE "$CONVENTIONAL_COMMIT_REGEX"; then
            echo "Error: PR title does not follow Conventional Commits format"
            echo "Expected format: <type>(<scope>): <description> or <type>: <description>"
            echo -e "\nValid types:"
            echo "$VALID_TYPES" | grep -v '^$' | sed 's/^/- /'
            echo -e "\nValid scopes:"
            echo "$VALID_SCOPES" | grep -v '^$' | grep -v '^#' | sed 's/^/- /'
            echo -e "\nCurrent title: $PR_TITLE"
            exit 1
          fi
          
          echo "PR title validation passed ✅"
          echo "Current title: $PR_TITLE"
